# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: rigid_body_1/pose
        pose2d: rigid_body_1/ground_pose
        frame_id: rigid_body_1/base_link

   #Use this format to create each new rigid body

   #'2':
   #    pose: rigid_body_2/pose
   #    pose2d: rigid_body_2/ground_pose
   #    frame_id: rigid_body_2/base_link
